package com.dyn.item.reference;

import java.util.Arrays;

import net.minecraftforge.fml.common.ModMetadata;

public class MetaData {
	public static ModMetadata init(ModMetadata metadata) {
		metadata.modId = Reference.MOD_ID;
		metadata.name = Reference.MOD_NAME;
		metadata.description = "Specialized Items and Blocks for the city server";
		metadata.url = "https://github.com/Digital-Youth-Network/Items";
		metadata.version = Reference.VERSION;
		metadata.authorList = Arrays.asList("Dom Amato");
		metadata.credits = "";
		metadata.autogenerated = false;
		return metadata;
	}
}
